using System.Linq;
using System.Threading.Tasks;
using Sparkitect.Generator.Modding.Analyzers;

namespace Sparkitect.Generator.Tests.Modding.Analyzers;

public sealed class HasIdentificationMisuseAnalyzerTests : AnalyzerTestBase<HasIdentificationMisuseAnalyzer>
{
    [Before(Test)]
    public void Setup()
    {
        TestSources.Add(TestData.GlobalUsings);
        TestSources.Add(TestData.ModdingCode);
        TestSources.Add(TestData.Sparkitect);
    }

    [Test]
    public async Task SupportedDiagnostics_ContainsExactlySpark0262()
    {
        var analyzer = new HasIdentificationMisuseAnalyzer();
        var ids = analyzer.SupportedDiagnostics.Select(d => d.Id).OrderBy(x => x).ToArray();
        await Assert.That(ids).IsEquivalentTo(new[] { "SPARK0262" });
    }

    [Test]
    public async Task UserSource_IHasIdentification_NoRegistryAttribute_Reports_SPARK0262()
    {
        var code = """
        using Sparkitect.Modding;

        namespace DiTest;

        public partial class Foo : IHasIdentification
        {
        }
        """;

        TestSources.Add(("Foo.cs", code));
        var diagnostics = await RunAnalyzerAsync();
        await AssertDiagnosticCount(diagnostics, "SPARK0262", 1);
    }

    [Test]
    public async Task UserSource_RegisteredConcrete_NoDiagnostic()
    {
        // A type that carries an IRegisterMarker-implementing attribute is exempt,
        // even when its base list still lists ': IHasIdentification' (the rule must
        // be agnostic to the residual user-source listing — auto-emit owns the slot).
        var marker = """
        using Sparkitect.Modding;

        namespace DiTest.Registries;

        [AttributeUsage(AttributeTargets.Class)]
        public sealed class RegisterFooAttribute : Attribute, IRegisterMarker
        {
            public RegisterFooAttribute(string id) { }
        }
        """;
        var code = """
        using Sparkitect.Modding;
        using DiTest.Registries;

        namespace DiTest;

        [RegisterFoo("foo")]
        public partial class Foo : IHasIdentification
        {
        }
        """;

        TestSources.Add(("RegisterFooAttribute.cs", marker));
        TestSources.Add(("Foo.cs", code));
        var diagnostics = await RunAnalyzerAsync();
        await AssertNoDiagnostics(diagnostics);
    }

    [Test]
    public async Task SgEmittedPartial_IHasIdentification_NoDiagnostic()
    {
        // SG-emitted source is filtered out by ConfigureGeneratedCodeAnalysis(None).
        // The .g.cs filename suffix is the canonical Roslyn marker for SG output.
        var code = """
        // <auto-generated/>
        using Sparkitect.Modding;

        namespace DiTest;

        partial class AutoEmittedFoo : IHasIdentification
        {
        }
        """;

        TestSources.Add(("AutoEmittedFoo.g.cs", code));
        var diagnostics = await RunAnalyzerAsync();
        await AssertNoDiagnostics(diagnostics);
    }
}
