using Sparkitect.Modding;

namespace Sparkitect.RenderGraph;

/// <summary>
/// Stock pass registry. Mods register concrete <see cref="IPass"/> implementations
/// via the generator-emitted <c>[RenderPassRegistry.RegisterPass(...)]</c> attribute;
/// the keyed-factory marker on <see cref="RegisterPass{TPass}"/> drives 49.2's
/// keyed-factory configurator generation, producing the
/// <c>RenderPassRegistry_RegisterPass_KeyedFactoryConfiguratorAttribute</c> consumers
/// pass to <see cref="Sparkitect.DI.IDIService.BuildFactoryContainer{TKey,TBase}"/>.
/// </summary>
/// <remarks>
/// <para>
/// Mirrors <c>samples/MinimalSampleMod/DummyRegistry.cs</c> per Phase 49 D-D4 — concrete
/// pass types carry no marker attribute themselves; they are plain classes implementing
/// <see cref="IPass"/> + <see cref="Sparkitect.Modding.IHasIdentification"/>, registered
/// through the standard registry-callback path.
/// </para>
/// <para>
/// At walking-skeleton scope <see cref="RegisterPass{TPass}"/> has an empty body — the
/// keyed-factory configurator generated by 49.2 carries the registration through the
/// factory pipeline. Phase 50+ may add side-effects here (e.g. shared metadata) without
/// breaking the keyed-factory wiring.
/// </para>
/// </remarks>
[Registry(Identifier = "render_pass")]
public partial class RenderPassRegistry : IRegistry
{
    /// <summary>
    /// Registration entrypoint for concrete pass types. The
    /// <see cref="KeyedFactoryGenerationMarkerAttribute{TBase}"/> drives 49.2's generator
    /// to emit the per-pass keyed factory + the per-(registry, method) configurator
    /// + the matching <c>…_KeyedFactoryConfiguratorAttribute</c>.
    /// </summary>
    [RegistryMethod]
    [KeyedFactoryGenerationMarker<IPass>]
    public void RegisterPass<TPass>(Identification id)
        where TPass : class, IPass, IHasIdentification
    {
        // Body intentionally empty at WS — keyed-factory configurator drives registration (D-D4).
    }

    public static string Identifier => "render_pass";

    public void Unregister(Identification id)
    {
        // No-op at WS — pass IDs are not tracked here at runtime; the keyed-factory
        // container is the source of truth. Phase 57 may revisit if runtime manipulation
        // (RG-25/RG-26) requires registry-side bookkeeping.
    }
}
