//HintName: RenderPassRegistry_OwningModule.g.cs
// <auto-generated/>
#pragma warning disable CS1591

namespace DiTest;

partial class RenderPassRegistry
{
    public static global::Sparkitect.Modding.Identification OwningModule
        => global::Sparkitect.Modding.TestModule.Identification;
}